type: charuco

boards:
  number_x_square: 11 #number of squares in the X direction
  number_y_square: 9 #number of squares the Y direction
  resolution_x: 2200 # horizontal resolution in pixel
  resolution_y: 1800 # vertical resolution in pixel
  length_square: 0.024 # parameters on the marker (can be kept as it is)
  length_marker: 0.018 # parameters on the marker (can be kept as it is)
  n_boards: 2 # number of boards used for calibration (for overlapping camera 1 is enough ...)
  boards_index: [] #leave it empty [] if the board index are ranging from zero to number_board
  thickness: 0.012
  square_size: 0.024 # size of each square of the board in cm/mm/whatever you want
  aruco_n: 6

detector:
  adaptiveThreshWinSizeStep: 1
  # detector_params.minDistanceToBorder = 1
  # detector_params.minGroupDistance = 0.1
  # detector_params.minMarkerDistanceRate = 0.05
  # detector_params.adaptiveThreshConstant = 1
  # detector_params.adaptiveThreshWinSizeMin = 3
  # detector_params.adaptiveThreshWinSizeMax = 53
  # detector_params.markerBorderBits = 2
  # detector_params.adaptiveThreshWinSizeStep = 10
