defaults:
  - cameras: basler
  - lights: gardasoft
  - strategies: light_sequence # null for no particular collection modes
  - postprocessings: none

paths:
  save_dir: "${oc.env:ROOT}/results/collection"

mode:
  val: manual
  valid_options:
    - manual
    - light_sequence

save:
  raw: false
  postprocessed: true
