defaults:
  - cameras: basler                           # ❌ Do not change
  - lights: none                              # ❌ Do not change
  - strategies: none                          # ❌ Do not change
  - postprocessings: none                     # ❌ Do not change

paths:
  save_dir: "${paths.collection_dir}"         # ❌ Do not change

mode:
  val: automatic                              # ✅ manual or automatic
  valid_options:
    - manual                                  # ❌ Do not change
    - automatic                               # ❌ Do not change
  one_cam_at_time: ${collect.one_cam_at_time} # ❌ Do not change
  in_ram: False                               # ❌ Do not change

save:
  raw: false                                  # ❌ Do not change
  postprocessed: true                         # ❌ Do not change

# lights:
#   channels: [8, 9, 10]
#   intensity: 1.0

