defaults:
  - _self_
  # - objects: charuco_boards/charuco_11x9_cvl.yaml
  # - collector: collector_default
  # - optimizer: adam
  # - scheduler: none
  # - loss: l1
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  src_dir: "${oc.env:ROOT}/src"
  mccalib_yaml: "${oc.env:ROOT}/configs/charuco_boards/charuco_cube.yaml"
  results_dir: "${oc.env:ROOT}/results"
  collection_dir: "${paths.results_dir}/collection"
  charuco_images_dir: "${paths.results_dir}/charuco_images"
  calib_results_dir: "${paths.results_dir}/calib_results"
  features_file: "${paths.collection_dir}/features.npy"
  log_file: "${paths.results_dir}/log.txt"

collect:
  do: True
  mode:
    val: "automatic"
    valid_options:
      - "manual"
      - "automatic"
  in_ram: False
  lights:
    channels: [8, 9, 10]
    intensity: 1.0

calibration:
  do: True

get_charuco_images: True
