defaults:
  - _self_
  - collectors: collector_default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  charuco_board_path: "${oc.env:ROOT}/data/charuco_boards/charuco_11x9_cvl.yaml"
  save_dir: "${oc.env:ROOT}/data/results/results"
  log_file: "${oc.env:ROOT}/data/results/log.txt"
  collected_images_dir:

calibration:
  collect_mode:
    val: "manual"
    valid_options:
      - "manual"
      - "automatic"
