defaults:
  - _self_
  - objects: charuco_boards/charuco_11x9_cvl
  - collector: collector_default
  - optimizer: adam
  - scheduler: none
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  save_dir: "${oc.env:ROOT}/results/results"
  log_file: "${oc.env:ROOT}/results/log.txt"
  collected_images_dir:

collect:
  mode:
    val: "manual"
    valid_options:
      - "manual"
      - "automatic"
  in_ram: True

calibration:
  device: cpu # cpu or gpu
  # in_ram: True
  iterations: 1000
  show_realtime: False
  objects_pose_fix:
    vals: []
    valid_options: [x, y, z, e1, e2, e3]
