defaults:
  - _self_
  - objects: charuco_boards/charuco_11x9_cvl.yaml
  - collector: collector_default
  - precalib: config
  - calib: config
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  src_dir: "${oc.env:ROOT}/src"
  results_dir: "${oc.env:ROOT}/results"
  collection_dir: "${paths.results_dir}/collection"
  charuco_images_dir: "${paths.results_dir}/charuco_images"
  calib_results_dir: "${paths.results_dir}/calib_results"
  features_file: "${paths.collection_dir}/features.npy"
  log_file: "${paths.results_dir}/log.txt"

collect:
  do: True
  mode:
    val: "manual"
    valid_options:
      - "manual"
      - "automatic"
  in_ram: False
  lights:
    channels: [8, 9, 10]
    intensity: 1.0

calibration:
  do: True
  device: cuda # cpu or cuda
  focal_length_prior: 0.016 # focal length prior in meters
  calib_params:
    iterations: 5000
    params: ${calib}
    lr: 0.0001
    reg_weight: 100
    early_stopping_diff: 0.0
    objects_pose_opt:
      position: [True, False, False]
      eul: [False, False, False]
    world_rotation:
      eul: [False, False, True]
    test: ${calibration.test}
    device: ${calibration.device}

  precalib_params:
    iterations: 2000
    params: ${precalib}
    lr: 0.05
    reg_weight: 0
    early_stopping_diff: 0.0
    test: ${calibration.test}
    device: ${calibration.device}
    objects_pose_opt:
      position: [True, False, False]
      eul: [False, False, False]
    world_rotation:
      eul: [False, False, True]

  percentage_points_min: 0.35
  test:
    init_show: False
    calib_show_realtime: True
    calib_show_last: True
    calib_show_rate: 500

get_charuco_images: True
