defaults:
  - _self_
  - objects: charuco_boards/charuco_11x9_cvl.yaml
  - collector: collector_default
  - precalib: config
  - calib: config
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  src_dir: "${oc.env:ROOT}/src"
  results_dir: "${oc.env:ROOT}/results"
  collection_dir: "${paths.results_dir}/collection"
  charuco_images_dir: "${paths.results_dir}/charuco_images"
  calib_results_dir: "${paths.results_dir}/calib_results"
  features_file: "${paths.collection_dir}/features.npy"
  log_file: "${paths.results_dir}/log.txt"

collect:
  do: True
  mode:
    val: "automatic"
    valid_options:
      - "manual"
      - "automatic"
  in_ram: False
  lights:
    channels: [8, 9, 10]
    intensity: 1.0

calibration:
  do: True
  device: cpu # cpu or cuda
  focal_length_prior: 0.016 # focal length prior in meters
  calib_params:
    iterations: 2500
    params: ${calib}
    lr: 0.001
    reg_weight: 0
    early_stopping_diff: 0.0
    objects_pose_opt:
      position: [1, 1, 0]
      eul: [0, 0, 0]
    test: ${calibration.test}
    device: ${calibration.device}

  precalib_params:
    iterations: 1000
    params: ${precalib}
    lr: 0.01
    reg_weight: 0
    early_stopping_diff: 0.0
    test: ${calibration.test}
    device: ${calibration.device}
    objects_pose_opt:
      position: [1, 1, 0]
      eul: [0, 0, 0]

  percentage_points_min: 0.35
  test:
    init_show: False
    calib_show_realtime: True
    calib_show_rate: 50

get_charuco_images: True
